version: '2'

services:
    transformers-pytorch:
        build: .
        restart: always
        ports:
          - 8888:8888
        logging:
            driver: json-file
            options:
                max-size: "20k"
